In [ ]:
#Q1
#(a)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr_reverse = arr[::-1]
print(arr_reverse)

#(b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten_arr = array1.flatten() #copy of array
raveled_arr = array1.ravel() #actual array

[5 4 6 3 2 1]


In [ ]:
#(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
arr1 == arr2
np.array_equal(arr1, arr2)

True

In [ ]:
#(d)
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
vals, counts = np.unique(x, return_counts=True)
most = vals[np.argmax(counts)]
idx = np.where(x == most)
print(most)
print(idx)

In [ ]:
#(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
#row wise
print(np.sum(gfg, axis = 1))
#col wise
print(np.sum(gfg, axis = 0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
#(f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
sum_dig = np.trace(n_array)
print(sum_dig)
eig_val = np.linalg.eigvals(n_array)
print(eig_val)
_, eig_vec = np.linalg.eig(n_array)
print(eig_vec)
inv = np.linalg.inv(n_array)
print(inv)
det = np.linalg.det(n_array)
print(det)

In [ ]:
#(g)
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

dot_product = np.dot(p, q)
print(dot_product)

###inefficient method :
#combined = np.stack((p.flatten(), q.flatten()), axis = 0)
#cov = np.cov(combined)
#print(cov)

#correct method :
#find p centered about it's mean of the features
p_c = p - p.mean(axis = 0)
#do the same for q
q_c = q - q.mean(axis = 0)
#now dim of p -> n * d1 and q -> n * d2
#now we want the featured to be multiplied so transpose p_c
ans = (p_c.T @ q_c)/(p.shape[0] - 1)
print(ans)

In [ ]:
#(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x,y)
print(inner)

#for outer product
a = x.flatten()
b = y.flatten()
outer = np.outer(a,b)
print(outer)

[[17 52]
 [13 62]]


In [ ]:
#cartesian product of two vectors :
#meth 1 :
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
a = x.flatten()
b = y.flatten()
for i in a :
  for j in b :
    print(f"({i}, {j})", end=" ")
  print()

#meth 2 :
from itertools import product
cartesian = np.array([np.concatenate([np.array([i]), np.array([j])]) for i, j in product(a,b)])
print(cartesian)

In [ ]:
#Q2 (a)
#(i)
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)

In [ ]:
#(ii)
array = np.array([[1, -2, 3], [-4, 5, -6]])

#for flattened array :
flatten_arr = array.flatten()
percentile_arr = np.percentile(flatten_arr, [25, 50, 75])
print(percentile_arr)

#for each row :
percentiles_row = np.percentile(array, [25, 50, 75], axis = 1)
print(percentiles_row)

#for each col :
percentiles_col = np.percentile(array, [25, 50, 75], axis = 0)
print(percentiles_col)

In [ ]:
#(iii)
array = np.array([[1, -2, 3], [-4, 5, -6]])

#for flattened array :
flatten_arr = array.flatten()
meanF = np.mean(flatten_arr)
medianF = np.median(flatten_arr)
sdF = np.std(flatten_arr)

#for each row :
meanR = np.mean(array, axis = 1)
medianR = np.median(array, axis = 1)
sdR = np.std(array, axis = 1)

#for each col :
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

In [ ]:
#(b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
ceil = np.ceil(a)
trun = np.trunc(a)
rounded = np.round(a)

In [ ]:
#Q3 (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
#(i)
sorted = np.sort(array)
#(ii)
sorted_ind = np.argsort(array)
#(iii)
smallest_4 = sorted[:4]
#(iv)
largest_5 = sorted[-5:][::-1]
print(largest_5)

In [ ]:
#(b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
#(i)
indices = np.where(array == np.floor(array))
print(array[indices])

indicesF = np.where(array != np.floor(array))
print(array[indicesF])

In [ ]:
#Q(4) (a)
import cv2
import numpy as np
from google.colab import files
from google.colab.patches import cv2_imshow

#upload the file from computer :
uploaded = files.upload()

Saving lena_color_256.jpg to lena_color_256.jpg


In [ ]:
def img_to_array(path) :
  #try to read image as gray scale :
  img = cv2.imread(path)

  if img is None :
    print("path not found")
    return

  #check if the image is 2D :
  if len(img.shape) == 2 :
    print("img is gray scale")
    np.savetxt("grayscale_image.txt", img, fmt='%d')
    print("saved as grayscale_image.txt")
  else :
    #read image as color image
    #convert the BGR to RGB
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    print("the image is RGB")
    # Flatten the RGB image to save
    img_rgb_flat = img_rgb.reshape(-1, 3)
    np.savetxt("rgb_image.txt", img_rgb_flat, fmt='%d')
    print("Saved as rgb_image.txt")